# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)


Lookup.create({ :id => 1, :category => 1, :code => 'root', :description => 'root' })
Lookup.create({ :id => 9, :category => 1, :code => 'work_type', :description => 'workout types' })
Lookup.create({ :id => 10, :category => 9, :code => 'run', :description => 'run' })
Lookup.create({ :id => 11, :category => 9, :code => 'bike', :description => 'bike' })
Lookup.create({ :id => 12, :category => 9, :code => 'swim', :description => 'swim' })
Lookup.create({ :id => 13, :category => 9, :code => 'other', :description => 'other' })

Lookup.create({ :id => 30, :category => 1, :code => 'jour_type', :description => 'journal entry type' })
Lookup.create({ :id => 31, :category => 30, :code => '1', :description => 'default' })
Lookup.create({ :id => 32, :category => 30, :code => '2', :description => 'quote' })
Lookup.create({ :id => 33, :category => 30, :code => '3', :description => 'other' })
Lookup.create({ :id => 34, :category => 1, :code => 'priority', :description => 'priority' })
Lookup.create({ :id => 35, :category => 34, :code => '1', :description => 'low' })
Lookup.create({ :id => 36, :category => 34, :code => '2', :description => 'medium' })
Lookup.create({ :id => 37, :category => 34, :code => '3', :description => 'high' })
Lookup.create({ :id => 38, :category => 34, :code => '4', :description => 'critical' })
Lookup.create({ :id => 39, :category => 1, :code => 'task_type', :description => 'task types' })
Lookup.create({ :id => 40, :category => 39, :code => '1', :description => 'home' })
Lookup.create({ :id => 41, :category => 39, :code => '2', :description => 'other' })
Lookup.create({ :id => 42, :category => 39, :code => '3', :description => 'tccf' })
Lookup.create({ :id => 43, :category => 39, :code => '4', :description => 'sidney' })
Lookup.create({ :id => 44, :category => 39, :code => '5', :description => 'cadboro' })
Lookup.create({ :id => 45, :category => 39, :code => '6', :description => 'layritz' })
Lookup.create({ :id => 46, :category => 39, :code => '7', :description => 'raceweb' })
Lookup.create({ :id => 47, :category => 1, :code => 'route', :description => 'route' })
Lookup.create({ :id => 48, :category => 47, :code => '115415', :description => 'esquimalt run (14)' })
Lookup.create({ :id => 49, :category => 47, :code => '488297', :description => 'christmas hill run (13)' })
Lookup.create({ :id => 50, :category => 47, :code => '115277', :description => 'waterfront ride' })
Lookup.create({ :id => 51, :category => 47, :code => '1077154 ', :description => 'peninsula,path,waterfront' })
Lookup.create({ :id => 52, :category => 47, :code => '491770', :description => 'songhees run' })
Lookup.create({ :id => 53, :category => 47, :code => '115570', :description => 'bear hill run' })
Lookup.create({ :id => 54, :category => 1, :code => 'interval', :description => 'reminder interval' })
Lookup.create({ :id => 55, :category => 54, :code => '7', :description => 'week' })
Lookup.create({ :id => 56, :category => 54, :code => '14', :description => 'two weeks' })
Lookup.create({ :id => 57, :category => 54, :code => 'm', :description => 'month' })
Lookup.create({ :id => 58, :category => 54, :code => '365', :description => 'year' })
Lookup.create({ :id => 59, :category => 47, :code => '649633', :description => 'selkirk run (7)' })
Lookup.create({ :id => 60, :category => 47, :code => '702047', :description => 'breakwater run (14)' })
Lookup.create({ :id => 61, :category => 47, :code => '817509', :description => 'gorge cuthbert run (12)' })
Lookup.create({ :id => 62, :category => 47, :code => '782559', :description => 'mt doug ritechs bogg run (24)' })
Lookup.create({ :id => 63, :category => 39, :code => '8', :description => 'race' })
Lookup.create({ :id => 64, :category => 1, :code => 'freq', :description => 'frequency' })
Lookup.create({ :id => 65, :category => 41, :code => '1', :description => 'daily' })
Lookup.create({ :id => 66, :category => 41, :code => '7', :description => 'weekly' })
Lookup.create({ :id => 67, :category => 41, :code => '14', :description => 'biweekly' })
Lookup.create({ :id => 68, :category => 41, :code => '15', :description => 'twice monthly' })
Lookup.create({ :id => 69, :category => 41, :code => '30', :description => 'monthly' })
Lookup.create({ :id => 70, :category => 41, :code => '365', :description => 'annualy' })

adam = Person.create({ :id => 1, :name => 'Adam Lawrence', :user_name => 'adam', :password => 'adam', :mail_url => 'http://mail.google.com/mail', :authority => 1, :birth_on => '1969-07-09'})
