Lookup.create({:category => 1, :code => 'root', :description => 'root' })
Lookup.create({:category => 1, :code => 'work_type', :description => 'workout types' })
Lookup.create({:category => 2, :code => 'run', :description => 'run' })
Lookup.create({:category => 2, :code => 'bike', :description => 'bike' })
Lookup.create({:category => 2, :code => 'swim', :description => 'swim' })
Lookup.create({:category => 2, :code => 'other', :description => 'other' })
Lookup.create({:category => 1, :code => 'jour_type', :description => 'journal entry type' })
Lookup.create({:category => 7, :code => '1', :description => 'default' })
Lookup.create({:category => 7, :code => '2', :description => 'quote' })
Lookup.create({:category => 7, :code => '3', :description => 'other' })
Lookup.create({:category => 1, :code => 'priority', :description => 'priority' })
Lookup.create({:category => 11, :code => '1', :description => 'low' })
Lookup.create({:category => 11, :code => '2', :description => 'medium' })
Lookup.create({:category => 11, :code => '3', :description => 'high' })
Lookup.create({:category => 11, :code => '4', :description => 'critical' })
Lookup.create({:category => 1, :code => 'task_type', :description => 'task types' })
Lookup.create({:category => 16, :code => '1', :description => 'home' })
Lookup.create({:category => 16, :code => '2', :description => 'other' })
Lookup.create({:category => 16, :code => '3', :description => 'tccf' })
Lookup.create({:category => 16, :code => '4', :description => 'sidney' })
Lookup.create({:category => 16, :code => '5', :description => 'cadboro' })
Lookup.create({:category => 16, :code => '6', :description => 'layritz' })
Lookup.create({:category => 16, :code => '7', :description => 'raceweb' })
Lookup.create({:category => 16, :code => '8', :description => 'race' })
Lookup.create({:category => 1, :code => 'route', :description => 'route' })
Lookup.create({:category => 25, :code => '115415', :description => 'esquimalt run (14)' })
Lookup.create({:category => 25, :code => '488297', :description => 'christmas hill run (13)' })
Lookup.create({:category => 25, :code => '115277', :description => 'waterfront ride' })
Lookup.create({:category => 25, :code => '1077154 ', :description => 'peninsula,path,waterfront' })
Lookup.create({:category => 25, :code => '491770', :description => 'songhees run' })
Lookup.create({:category => 25, :code => '115570', :description => 'bear hill run' })
Lookup.create({:category => 25, :code => '649633', :description => 'selkirk run (7)' })
Lookup.create({:category => 25, :code => '702047', :description => 'breakwater run (14)' })
Lookup.create({:category => 25, :code => '817509', :description => 'gorge cuthbert run (12)' })
Lookup.create({:category => 25, :code => '782559', :description => 'mt doug ritechs bogg run (24)' })
Lookup.create({:category => 1, :code => 'freq', :description => 'frequency' })
Lookup.create({:category => 36, :code => '1', :description => 'daily' })
Lookup.create({:category => 36, :code => '7', :description => 'weekly' })
Lookup.create({:category => 36, :code => '14', :description => 'biweekly' })
Lookup.create({:category => 36, :code => '15', :description => 'twice monthly' })
Lookup.create({:category => 36, :code => '30', :description => 'monthly' })
Lookup.create({:category => 36, :code => '365', :description => 'annualy' })

adam = Person.create({ :username => 'adam', :password => 'adam_pass', :password_confirmation => 'adam_pass', :born_on => 35.years.ago, :authority => '3', :mail_url => 'http://mail.google.com', :map_center => '48.468141,-123.358612'})
quinn = Person.create({ :username => 'quinn', :password => 'quinn_pass', :password_confirmation => 'quinn_pass', :born_on => 45.years.ago, :authority => '3', :mail_url => 'http://mail.yahoo.com', :map_center => '48.468141,-123.358612'})
dave = Person.create({ :username => 'dave', :password => 'dave_pass', :password_confirmation => 'dave_pass', :born_on => 55.years.ago, :authority => '3', :mail_url => 'http://mail.hotmail.com', :map_center => '48.468141,-123.358612'})

Link.create({ :person => adam, :url => 'http://www.nba.com', :name => 'nba', :tags => 'sports', :comments => 'stupid league', :clicks => 15, :last_clicked_on => '2013-02-01', :expires_on => nil })
Link.create({ :person => adam, :url => 'http://www.nhl.com', :name => 'nhl', :tags => 'sports', :comments => 'greedy fuckers', :clicks => 5, :last_clicked_on => '2013-02-10', :expires_on => nil })

Contact.create({ :person => adam, :name => 'mom', :email => 'lizburke48@hotmail.com', :phone_home => '250-347-9021', :phone_work => '250-342-6416', :address => 'box 100', :city => 'radium', :tags => 'family', :comments => 'makes cookies'})
Contact.create({ :person => adam, :name => 'dad', :email => 'jerrylawr@gmail.com', :phone_home => '250-344-6584', :phone_work => '250-344-6584', :address => 'box 200', :city => 'golden', :tags => 'family', :comments => 'makes houses'})
Contact.create({ :person => adam, :name => 'cate', :email => 'cate@raceweb,ca', :phone_home => '250-658-4719', :phone_work => '250-342-6416', :address => '1175 gerda', :city => 'victoria', :tags => 'family', :comments => 'makes crafts'})
Contact.create({ :person => adam, :name => 'colin', :email => 'colin@raceweb,ca', :phone_home => '250-658-4719', :phone_work => '250-342-6416', :address => '1175 gerda', :city => 'victoria', :tags => 'family', :comments => 'makes trouble'})
Contact.create({ :person => adam, :name => 'quinn', :email => 'quinn@raceweb,ca', :phone_home => '250-414-0106', :phone_work => '250-342-6416', :address => '123 paradise st', :city => 'victoria', :tags => 'family', :comments => 'makes nothing'})
Contact.create({ :person => adam, :name => 'else', :email => 'else@raceweb,ca', :phone_home => '250-414-0106', :phone_work => '250-342-6416', :address => '123 paradise st', :city => 'victoria', :tags => 'family', :comments => 'makes cookies'})
Contact.create({ :person => adam, :name => 'darby', :email => 'darby@raceweb,ca', :phone_home => '250-881-2818', :phone_work => '250-342-6416', :address => '42-330 tyee rd', :city => 'victoria', :tags => 'dog', :comments => 'makes poop'})
Contact.create({ :person => adam, :name => 'chloe', :email => 'chloe@raceweb,ca', :phone_home => '250-658-4719', :phone_work => '250-342-6416', :address => 'box 100', :city => 'victoria', :tags => 'dog', :comments => 'makes poop'})
Contact.create({ :person => adam, :name => 'mark', :email => 'mark@raceweb,ca', :phone_home => '250-686-3325', :phone_work => '250-342-6416', :address => '123 belton ave', :city => 'victoria', :tags => 'friend', :comments => 'makes music'})
Contact.create({ :person => adam, :name => 'eva', :email => 'eva@raceweb,ca', :phone_home => '250-514-4727', :phone_work => '250-342-6416', :address => '123 belton ave', :city => 'victoria', :tags => 'friend', :comments => 'makes dinner'})
Contact.create({ :person => quinn, :name => 'mom', :email => 'mom@raceweb,ca', :phone_home => '250-414-0106', :phone_work => '250-342-6416', :address => '123 paradise st', :city => 'victoria', :tags => 'family', :comments => 'makes dinner'})
Contact.create({ :person => quinn, :name => 'dad', :email => 'dad@raceweb,ca', :phone_home => '250-881-2818', :phone_work => '250-342-6416', :address => '42-330 tyee rd', :city => 'victoria', :tags => 'family', :comments => 'makes dinner'})
